### ISSUE TITLE
Additional Integrations

### ISSUE THREAD

**Issue by kidGodzilla** [kidGodzilla/electric-love#14]
Hello!

Looking for additional analytics or product integrations?

Let us know, and we will work with you to get it added!

**Comment by juan-m12i** [comment]
hi there, it would be nice to add Piwik (Matomo). Happy to contribute if ok

**Comment by aviggiano** [comment]
Hey
Would you accept a PR integrating AWS Cognito/Kinesis?

**Comment by kidGodzilla** [comment]
Definitely would accept any PRs for new integrations.
