### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by aviggiano** [kidGodzilla/electric-love#29]
I believe the README section regarding "fully tested / considered stable & production-ready" integrations could be a bit more clear. 

Perhaps adding a table, instead of an unordered list, containing integration, and a checkmark for stable, would be better. E.g.:

Integration | Stable
------------ | -------------
Google Analytics | ✔️
MyAnalytics.com | 
Facebook | ✔️

**Comment by kidGodzilla** [comment]
Agreed!

**Comment by kidGodzilla** [comment]
Completed. Thanks!
