### ISSUE TITLE
Breaks on GTM because of ES6

### ISSUE THREAD

**Issue by svaldesm** [kidGodzilla/electric-love#30]
Hi, 

Trying to add the code to GTM, it breaks. The explanation of GTM is this:

> Error at line 202, character 45: This language feature is only supported for ECMASCRIPT6 mode or better: default parameter.

The line that is affected is this one:

`            page: function (category, name, properties={}) {`

Is there a way to fix this?

Thanks!

**Comment by svaldesm** [comment]
A developer I know suggested this solution, but I'm not sure if it solves the issue:

`page: function (category, name, properties) {
  properties = properties || {};`

Glad to know if this is the case.

Thanks again.

**Comment by kidGodzilla** [comment]
Fixing, 0.2.22 should resolve this. Thanks for reporting!
