### ISSUE TITLE
Initialising and including scripts

### ISSUE THREAD

**Issue by robertvanhoesel** [kidGodzilla/electric-love#9]
Hi James, this project already looks interesting! Do you have any plans on dynamically adding and initialising the required scripts from integrations? Eg. when I add Intercom as an integration, I can initialise and boot Intercom through Electric love, just like analytics.js (Segment) does?

**Comment by kidGodzilla** [comment]
That's interesting. Then it becomes sort of like a composable config file that compiles into your analytics stack.
